#!/usr/bin/env python3

import os


# ========= ENV =========
os.environ["GDAL_NUM_THREADS"] = "ALL_CPUS"
os.environ["NUM_THREADS"] = "ALL_CPUS"


from rasterio.enums import ColorInterp
from rasterio.windows import Window
from multiprocessing import Pool
from pathlib import Path
import threading
import argparse
import rasterio
import logging
import signal
import numpy
import uuid
import time
import sys


# ========= LOG =========
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)


# ========= SIGNALS =========
def setup_signals():
	signal.signal(signal.SIGINT, lambda sig, frame: (
		LOGGER.info("Received 'SIGINT' signal. Exitting..."),

		sys.exit(0)
	))

	signal.signal(signal.SIGTERM, lambda sig, frame: (
		LOGGER.info("Received 'SIGTERM' signal. Exitting..."),

		sys.exit(0)
	))


# ========= COMMAND =========
def setup_command():
	parser = argparse.ArgumentParser(description="Convert DEM raster to RGB raster (Terrain-RGB)")
	parser.add_argument("-out", "--output", required=True, type=Path, help="Output RGB raster file path")
	parser.add_argument("-in", "--input", required=False, type=Path, help="Input DEM raster file path")
	parser.add_argument("-b", "--base-val", required=False, type=float, default=-10000, help="Base value")
	parser.add_argument("-i", "--interval", required=False, type=float, default=0.1, help="Interval")
	parser.add_argument("-w", "--workers", required=False, type=int, default=1, help="Number of worker processes")
	parser.add_argument("-c", "--compression", required=False, action="store_true", help="Enable compression for output")
	parser.add_argument("-od", "--output-driver", required=False, type=str, default="GTiff", help="Output driver")
	parser.add_argument("-bc", "--band-count", required=False, choices=[3, 4], default=3, help="Output band count")

	return parser


# ========= ENCODE =========
def data_to_rgb(args):
	data, window, convert_args = args

	mask = numpy.isclose(data, convert_args["nodata"]) if convert_args["nodata"] is not None else None

	data = (data.astype(numpy.float64, copy=False) - convert_args["base_val"]) / convert_args["interval"]

	rgb = numpy.empty((convert_args["band_count"], *data.shape), dtype=numpy.uint8)
	rgb[2] = data % 256
	rgb[1] = (data // 256) % 256
	rgb[0] = (data // (256 * 256)) % 256

	if convert_args["band_count"] == 4:
		rgb[3] = 255

		if mask is not None:
			rgb[3][mask] = 0

	return rgb, window


# ========= MAIN =========
if __name__ == "__main__":
	if threading.current_thread() is threading.main_thread():
		setup_signals()

	parser = setup_command()

	args = parser.parse_args()

	input = args.input if args.input else args.output

	LOGGER.info(f"Converting DEM raster to RGB raster (Terrain-RGB) '{input}' -> '{args.output}'...")

	t0 = time.time()

	tmp_file_path = None

	with rasterio.open(input, "r") as src:
		profile = src.profile.copy()
		profile.update(
			dtype="uint8",
			count=args.band_count,
			photometric="RGB",
			nodata=None,
			tiled=True,
			blockxsize=512,
			blockysize=512,
			bigtiff="YES",
		)

		if args.output_driver:
			profile.update(
				driver=args.output_driver,
			)

		if args.compression:
			profile.update(
				compress="LZW",
				predictor=2,
			)

		if input == args.output:
			tmp_file_path = input.with_name(f"{input.stem}_{uuid.uuid4().hex}{input.suffix}")
		else:
			tmp_file_path = args.output

			tmp_file_path.unlink(missing_ok=True)

		with rasterio.open(tmp_file_path, "w", **profile) as dst:
			block_h, block_w = src.block_shapes[0]

			convert_args = {
				"base_val": args.base_val,
				"interval": args.interval,
				"nodata": src.nodata,
				"band_count": args.band_count,
			}

			def window_generator():
				for y in range(0, src.height, block_h):
					h = min(block_h, src.height - y)

					for x in range(0, src.width, block_w):
						window = Window(x, y, min(block_w, src.width - x), h)

						yield (src.read(1, window=window), window, convert_args)

			workers = max(1, args.workers)

			# Create workers
			if workers > 1:
				pool = Pool(workers)
			else:
				pool = None

			try:
				if pool:
					for rgb, window in pool.imap_unordered(data_to_rgb, window_generator()):
						dst.write(rgb, window=window)
				else:
					for args in window_generator():
						rgb, window = data_to_rgb(args)

						dst.write(rgb, window=window)

				if args.band_count == 3:
					dst.colorinterp = (
						ColorInterp.red,
						ColorInterp.green,
						ColorInterp.blue,
					)
				else:
					dst.colorinterp = (
						ColorInterp.red,
						ColorInterp.green,
						ColorInterp.blue,
						ColorInterp.alpha,
					)
			finally:
				if pool:
					pool.close()
					pool.join()

	if input == args.output:
		if tmp_file_path:
			tmp_file_path.replace(input)

	LOGGER.info(f"Converted DEM raster to RGB raster (Terrain-RGB) '{input}' -> '{args.output}' in {time.time() - t0:.2f}s!")
