#!/usr/bin/env python3

from rasterio.warp import reproject, calculate_default_transform
from rasterio.enums import Resampling
from multiprocessing import Pool
from pathlib import Path
from PIL import Image
import mercantile
import threading
import argparse
import rasterio
import sqlite3
import logging
import signal
import numpy as np
import math
import time
import sys
import io

# ========= LOGS =========
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)

# ========= CONSTANTS =========
SPHERICAL_RADIUS = 6378137.0
MAX_LON = 180
MAX_LAT = 90
MAX_CAL_LAT = 85.051129
INITIAL_RESOLUTION = 156543.03392804097
TARGET_CRS = "EPSG:3857"

# ========= GLOBALS (per worker) =========
_worker_src = None
_worker_tile_size = None

# ========= SIGNALS =========
def setup_signals():
    signal.signal(signal.SIGINT, lambda sig, frame: (
        LOGGER.info("Received 'SIGINT' signal. Exitting..."),
        sys.exit(0)
    ))

    signal.signal(signal.SIGTERM, lambda sig, frame: (
        LOGGER.info("Received 'SIGTERM' signal. Exitting..."),
        sys.exit(0)
    ))

# ========= CLI =========
def setup_command():
    parser = argparse.ArgumentParser(description="Convert GeoTIFF to MBTiles raster")
    parser.add_argument("-i", "--input", required=True, type=Path, help="Input GeoTIFF")
    parser.add_argument("-o", "--output", required=True, type=Path, help="Output MBTiles")
    parser.add_argument("-w", "--workers", type=int, default=1, help="Worker processes")
    parser.add_argument("-bz", "--batch-size", type=int, default=1000, help="Commit batch size")
    parser.add_argument("-mi", "--metadata-index", required=False, action="store_true", help="Create metadata unique index")
    parser.add_argument("-ti", "--tiles-index", required=False, action="store_true", help="Create tiles unique index")
    parser.add_argument("-mj", "--metadata-json", required=False, type=str, help="Metadata JSON string to update metadata table")
    parser.add_argument("-r", "--resampling", required=False, choices=["nearest", "bilinear", "cubic", "lanczos"], default="lanczos", help="Resampling method to create tiles")

    return parser

# ========= UTILS =========
def get_maxzoom_from_resolution(src):
    transform, _, _ = calculate_default_transform(
        src.crs, TARGET_CRS,
        src.width, src.height,
        *src.bounds
    )

    res = max(abs(transform.a), abs(transform.e))
    return math.ceil(math.log2(INITIAL_RESOLUTION / res))


def parse_bounds(bounds):
	parts = bounds.split(",")

	if len(parts) != 4:
		raise ValueError("Invalid bounds format")

	bounds = [float(x) for x in parts]

	if bounds[0] >= bounds[2] or bounds[0] < -MAX_LON or bounds[2] > MAX_LON or bounds[1] >= bounds[3] or bounds[1] < -MAX_LAT or bounds[3] > MAX_LAT:
		raise ValueError("Invalid bounds")

	return bounds


def encode_array(bounds):
	return ",".join(str(x) for x in bounds)


def limit_value(value, min = None, max = None):
	if min is not None and value < min:
		value = min

	if max is not None and value > max:
		value = max

	return value


def lonlat4326_to_xy3857(lon, lat):
	return limit_value(lon, -MAX_LON, MAX_LON) * math.pi / MAX_LON * SPHERICAL_RADIUS, math.log(math.tan(math.pi * (limit_value(lat, -MAX_CAL_LAT, MAX_CAL_LAT) + MAX_LAT) / (2 * MAX_LON))) * SPHERICAL_RADIUS


def xy3857_to_lonlat4326(x, y):
	return limit_value(x / SPHERICAL_RADIUS * MAX_LON / math.pi, -MAX_LON, MAX_LON), limit_value(math.atan(math.sinh(y / SPHERICAL_RADIUS)) * MAX_LON / math.pi, -MAX_CAL_LAT, MAX_CAL_LAT)


def get_xyz_from_lonlatz(lon, lat, z, scheme="tms"):
	max_tile = 1 << z

	x = (0.5 + limit_value(lon, -MAX_LON, MAX_LON) / (2 * MAX_LON)) * max_tile
	y = (0.5 - math.log(math.tan(math.pi * (limit_value(lat, -MAX_CAL_LAT, MAX_CAL_LAT) + MAX_LAT) / (2 * MAX_LON))) / (2 * math.pi)) * max_tile

	if scheme == "tms":
		y = max_tile - y

	return [limit_value(math.floor(x), 0, max_tile - 1), limit_value(math.floor(y), 0, max_tile - 1), z]


def get_lonlat_from_xyz(x, y, z, position, scheme="tms"):
	max_tile = 1 << z

	if scheme == "tms":
		y = max_tile - 1 - y

	if position == "center":
		x += 0.5
		y += 0.5
	elif position == "bottom-right":
		x += 1
		y += 1

	return [(2 * MAX_LON) * (x / max_tile - 0.5), ((2 * MAX_LON) * math.atan(math.exp(math.pi * (1 - 2 * y / max_tile))) / math.pi) - MAX_LAT]


def get_bbox_from_tiles(x_min, y_min, x_max, y_max, z, scheme = "tms"):
	[lon_min, lat_max] = get_lonlat_from_xyz(x_min, y_min, z, "top-left", scheme)
	[lon_max, lat_min] = get_lonlat_from_xyz(x_max, y_max, z, "bottom-right", scheme)

	if lon_min > lon_max:
		[lon_min, lon_max] = [lon_max, lon_min]

	if lat_min > lat_max:
		[lat_min, lat_max] = [lat_max, lat_min]

	return [lon_min, lat_min, lon_max, lat_max]


def get_tiles_from_bbox(bbox, z, scheme = "tms"):
	[x_min, y_min] = get_xyz_from_lonlatz(bbox[0], bbox[3], z, scheme)
	[x_max, y_max] = get_xyz_from_lonlatz(bbox[2], bbox[1], z, scheme)

	if x_min > x_max:
		[x_min, x_max] = [x_max, x_min]

	if y_min > y_max:
		[y_min, y_max] = [y_max, y_min]

	return [x_min, y_min, x_max, y_max]


def get_cover_bbox(bbox1, bbox2):
	if bbox1 and bbox2:
		return [
			bbox1[0] if bbox1[0] < bbox2[0] else bbox2[0],
			bbox1[1] if bbox1[1] < bbox2[1] else bbox2[1],
			bbox1[2] if bbox1[2] > bbox2[2] else bbox2[2],
			bbox1[3] if bbox1[3] > bbox2[3] else bbox2[3],
		]
	elif bbox1:
		return bbox1
	elif bbox2:
		return bbox2

	return None


def get_intersect_bbox(bbox1, bbox2):
	if bbox1 and bbox2:
		minLon = bbox1[0] if bbox1[0] > bbox2[0] else bbox2[0]
		minLat = bbox1[1] if bbox1[1] > bbox2[1] else bbox2[1]
		maxLon = bbox1[2] if bbox1[2] < bbox2[2] else bbox2[2]
		maxLat = bbox1[3] if bbox1[3] < bbox2[3] else bbox2[3]

		if (minLon >= maxLon or minLat >= maxLat):
			return None
	elif bbox1:
		return bbox1
	elif bbox2:
		return bbox2

	return None
def get_mbtiles_metadata(cur, name):
	if name is not None:
		cur.execute("SELECT name, value FROM metadata WHERE name = ?;", (name,))
		row = cur.fetchone()
		if row:
			return row[1]


def get_mbtiles_metadatas(cur):
	cur.execute("SELECT name, value FROM metadata;")
	rows = cur.fetchall()
	if rows:
		return { name: value for name, value in rows }


def get_mbtiles_bounds_from_tiles(cur, scheme="tms"):
	cur.execute("SELECT zoom_level, MIN (tile_column), MAX (tile_column), MIN (tile_row), MAX (tile_row) FROM tiles GROUP BY zoom_level;")
	rows = cur.fetchall()
	if not rows:
		return None

	z, x_min, x_max, y_min, y_max = rows[0]
	bounds = get_bbox_from_tiles(x_min, y_min, x_max, y_max, z, scheme)

	if len(rows) > 1:
		for row in rows[1:]:
			z, x_min, x_max, y_min, y_max = row

			bounds = get_cover_bbox(bounds, get_bbox_from_tiles(x_min, y_min, x_max, y_max, z, scheme))

	bounds[0] = limit_value(bounds[0], -MAX_LON, MAX_LON)
	bounds[2] = limit_value(bounds[2], -MAX_LON, MAX_LON)
	bounds[1] = limit_value(bounds[1], -MAX_CAL_LAT, MAX_CAL_LAT)
	bounds[3] = limit_value(bounds[3], -MAX_CAL_LAT, MAX_CAL_LAT)

	return bounds


def get_mbtiles_zoom_level_from_tiles(cur, min):
	if min:
		cur.execute("SELECT MIN (zoom_level) FROM tiles;")
	else:
		cur.execute("SELECT MAX (zoom_level) FROM tiles;")

	row = cur.fetchone()
	if not row:
		return None

	return row[0]


def get_mbtiles_format_from_tiles(cur):
	cur.execute("SELECT tile_data FROM tiles LIMIT 1;")
	row = cur.fetchone()
	if not row:
		return None

	if row[0].startswith(b"\x89PNG\r\n\x1a\n"):
		return "png"
	elif row[0].startswith(b"\xff\xd8"):
		return "jpeg"
	elif row[0].startswith((b"GIF87a", b"GIF89a")):
		return "gif"
	elif row[0].startswith(b"RIFF") and row[0][8:12] == b"WEBP":
		return "webp"
	else:
		return "pbf"


# ========= WORKER INIT =========
def worker_init(src_path, tile_size):
    global _worker_src, _worker_tile_size
    _worker_src = rasterio.open(src_path)
    _worker_tile_size = tile_size

# ========= RENDER =========
def render_tile(tile):
    global _worker_src, _worker_tile_size

    bbox = mercantile.xy_bounds(tile)

    dst_transform = rasterio.transform.from_bounds(
        bbox.left, bbox.bottom,
        bbox.right, bbox.top,
        _worker_tile_size, _worker_tile_size
    )

    band_count = _worker_src.count

    # Đọc tối đa 4 band
    out_bands = 4
    data = np.zeros((out_bands, _worker_tile_size, _worker_tile_size), dtype=np.uint8)

    src_indexes = list(range(1, min(band_count, 3) + 1))

    # Nếu có alpha thì lấy luôn
    if band_count >= 4:
        src_indexes.append(4)

    tmp = np.zeros((len(src_indexes), _worker_tile_size, _worker_tile_size), dtype=np.uint8)

    reproject(
        source=rasterio.band(_worker_src, src_indexes),
        destination=tmp,
        src_transform=_worker_src.transform,
        src_crs=_worker_src.crs,
        dst_transform=dst_transform,
        dst_crs=TARGET_CRS,
        resampling=Resampling.bilinear,
    )

    if tmp.shape[0] == 3:
        data[0:3] = tmp
        data[3] = 255
    else:
        data = tmp

    if not data[:3].any():
        return None

    img = Image.fromarray(np.transpose(data, (1, 2, 0)), "RGBA")

    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)

    return (tile.z, tile.x, tile.y, buf.getvalue())


# ========= MBTILES =========
def connect(file_path, ensure_schema = None):
  conn = sqlite3.connect(file_path)
  cur = conn.cursor()

  cur.execute("PRAGMA journal_mode = OFF;")
  cur.execute("PRAGMA synchronous = OFF;")
  cur.execute("PRAGMA foreign_keys = OFF;")
  cur.execute("PRAGMA encoding = 'UTF-8';")
  cur.execute("PRAGMA page_size = 65536;")

  if ensure_schema:
    cur.execute("CREATE TABLE IF NOT EXISTS metadata (name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name));")
    cur.execute("CREATE TABLE IF NOT EXISTS tiles (zoom_level INTEGER NOT NULL, tile_column INTEGER NOT NULL, tile_row INTEGER NOT NULL, tile_data BLOB NOT NULL, UNIQUE (zoom_level, tile_column, tile_row));")

  return conn, cur


def create_unique_indexes(cur, metadata_index, tiles_index):
  def has_unique_index(table_name, column_names):
    cur.execute(f"PRAGMA index_list ({table_name});")
    indexes = cur.fetchall()
    if not indexes:
      return False

    for _, index_name, is_unique, *_ in indexes:
      if not is_unique:
        continue

      cur.execute(f"PRAGMA index_info ({index_name});")
      columns = cur.fetchall()
      if not columns:
        continue

      index_cols = [col[2] for col in columns]
      if index_cols == column_names:
        return True

    return False

  if metadata_index and not has_unique_index("metadata", ["name"]):
    cur.execute("CREATE UNIQUE INDEX metadata_index ON metadata (name);")

  if tiles_index and not has_unique_index("tiles", ["zoom_level", "tile_column", "tile_row"]):
    cur.execute("CREATE UNIQUE INDEX tiles_index ON tiles (zoom_level, tile_column, tile_row);")


def update_metadata(conn, cur, metadata_json, merge_bounds):
	final_metadata = {}

	origin_metadatas = get_mbtiles_metadatas(cur)
	if origin_metadatas:
		final_metadata.update(origin_metadatas)

	if metadata_json:
		final_metadata.update(metadata_json)

	if "name" not in final_metadata:
		final_metadata["name"] = "Unknown"

	if "description" not in final_metadata:
		final_metadata["description"] = final_metadata["name"]

	if "attribution" not in final_metadata:
		final_metadata["attribution"] = "<b>Viettel HighTech</b>"

	if "version" not in final_metadata:
		final_metadata["version"] = "1.0.0"

	if "type" not in final_metadata:
		final_metadata["type"] = "overlay"

	if "format" not in final_metadata:
		tile_format = get_mbtiles_format_from_tiles(cur)
		if tile_format is not None:
			final_metadata["format"] = tile_format

	minzoom = None
	if "minzoom" not in final_metadata:
		minzoom = get_mbtiles_zoom_level_from_tiles(cur, True)
		if minzoom is not None:
			final_metadata["minzoom"] = str(minzoom)

	maxzoom = None
	if "maxzoom" not in final_metadata:
		maxzoom = get_mbtiles_zoom_level_from_tiles(cur, False)
		if maxzoom is not None:
			final_metadata["maxzoom"] = str(maxzoom)

	if "scheme" not in final_metadata:
		final_metadata["scheme"] = "tms"

	bounds = None
	if "bounds" not in final_metadata:
		bounds = get_mbtiles_bounds_from_tiles(cur, final_metadata["scheme"])
		if bounds:
			final_metadata["bounds"] = encode_array(bounds)
	else:
		bounds = parse_bounds(final_metadata["bounds"])

	if "center" not in final_metadata:
		if bounds and minzoom is not None and maxzoom is not None:
			final_metadata["center"] = encode_array([(bounds[0] + bounds[2]) / 2, (bounds[1] + bounds[3]) / 2, math.floor((minzoom + maxzoom) / 2)])

	insert_query = "INSERT INTO metadata (name, value) VALUES (?, ?) ON CONFLICT (name) DO UPDATE SET value = excluded.value;"

	conn.execute("BEGIN;")

	for key, value in final_metadata.items():
		cur.execute(insert_query, (key, value))

	conn.execute("COMMIT;")


def insert_tile(cur, z, x, y, data):
    tms_y = (2 ** z - 1) - y
    cur.execute(
        "INSERT OR REPLACE INTO tiles VALUES (?, ?, ?, ?);",
        (z, x, tms_y, data)
    )

# ========= MAIN =========
if __name__ == "__main__":
    if threading.current_thread() is threading.main_thread():
        setup_signals()

    parser = setup_command()
    args = parser.parse_args()

    # Parse and validate metadata json
    metadata_json = None
    if args.metadata_json:
      try:
        metadata_json = json.loads(args.metadata_json)
        if not isinstance(metadata_json, dict):
          raise ValueError("Metadata JSON must be an object")
      except Exception as e:
        raise ValueError(f"Invalid Metadata JSON: {e}")

    workers = max(1, args.workers)

    LOGGER.info(f"Converting GeoTIFF → MBTiles: {args.input} -> {args.output}")

    t0 = time.time()
    args.output.unlink(missing_ok=True)

    with rasterio.open(args.input) as src:
        bounds = src.bounds
        auto_maxzoom = get_maxzoom_from_resolution(src)

    minzoom = args.min_zoom if args.min_zoom is not None else 0
    maxzoom = args.max_zoom if args.max_zoom is not None else auto_maxzoom

    LOGGER.info(f"Zoom range: {minzoom}..{maxzoom}")

    conn, cur = connect(args.output)

    if args.metadata_index or args.tiles_index:
      LOGGER.info(f"Creating indexes MBTiles '{args.output}'...")

      create_unique_indexes(cur, args.metadata_index, args.tiles_index)

    tile_count = 0

    for z in range(minzoom, maxzoom + 1):
        LOGGER.info(f"Processing zoom {z}")

        tiles = mercantile.tiles(
            bounds.left, bounds.bottom,
            bounds.right, bounds.top,
            z
        )

        if workers == 1:
            worker_init(str(args.input), args.tile_size)

            for tile in tiles:
                res = render_tile(tile)
                if res is None:
                    continue

                tz, x, y, data = res
                insert_tile(cur, tz, x, y, data)

                tile_count += 1
                if tile_count % args.batch_size == 0:
                    conn.commit()
                    LOGGER.info(f"Committed {tile_count} tiles")

        else:
            with Pool(
                processes=workers,
                initializer=worker_init,
                initargs=(str(args.input), args.tile_size)
            ) as pool:
                for res in pool.imap(render_tile, tiles, chunksize=1):
                    if res is None:
                        continue

                    tz, x, y, data = res
                    insert_tile(cur, tz, x, y, data)

                    tile_count += 1
                    if tile_count % args.batch_size == 0:
                        conn.commit()
                        LOGGER.info(f"Committed {tile_count} tiles")

        conn.commit()

    conn.close()

    LOGGER.info(f"Done: {tile_count} tiles in {time.time() - t0:.2f}s")
