#!/usr/bin/env python3

import os


# ========= ENV =========
os.environ["GDAL_NUM_THREADS"] = "ALL_CPUS"
os.environ["NUM_THREADS"] = "ALL_CPUS"


from rasterio.warp import calculate_default_transform, reproject
from rasterio.enums import Resampling, ColorInterp
from rasterio.windows import Window
from rasterio.vrt import WarpedVRT
from pathlib import Path
import threading
import argparse
import rasterio
import logging
import signal
import numpy
import uuid
import time
import sys


# ========= LOG =========
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)


# ========= SIGNALS =========
def setup_signals():
	signal.signal(signal.SIGINT, lambda sig, frame: (
		LOGGER.info("Received 'SIGINT' signal. Exitting..."),

		sys.exit(0)
	))

	signal.signal(signal.SIGTERM, lambda sig, frame: (
		LOGGER.info("Received 'SIGTERM' signal. Exitting..."),

		sys.exit(0)
	))


# ========= COMMAND =========
def setup_command():
	parser = argparse.ArgumentParser(description="Reproject raster")
	parser.add_argument("-o", "--output", required=True, type=Path, help="Output raster file path")
	parser.add_argument("-i", "--input", required=False, type=Path, help="Input raster file path")
	parser.add_argument("-w", "--workers", required=False, type=int, default=1, help="Number of worker processes")
	parser.add_argument("-c", "--compression", required=False, action="store_true", help="Enable compression for output")
	parser.add_argument("-r", "--resampling", required=False, choices=["nearest", "bilinear", "cubic", "lanczos"], default="lanczos", help="Resampling method to reproject")
	parser.add_argument("-e", "--expand", required=False, choices=["rgb", "rgba"], help="Expand to RGB/RGBA")
	parser.add_argument("-t", "--target", required=False, type=str, help="Target SRS")
	parser.add_argument("-od", "--output-driver", required=False, type=str, default="GTiff", help="Output driver")

	return parser


# ========= UTILS =========
def expand_to_rgba(src, dst_path, compression, rgb, output_driver="GTiff"):
	band_count = 3 if rgb else 4

	profile = src.profile.copy()
	profile.update(
		count=band_count,
		dtype="uint8",
		photometric="RGB",
		interleave="PIXEL",
		tiled=True,
		blockxsize=512,
		blockysize=512,
		bigtiff="YES",
	)

	if output_driver:
		profile.update(
			driver=output_driver,
		)

	if compression:
		profile.update(
			compress="LZW",
			predictor=2,
		)

	# ===== Build LUT =====
	lut = numpy.zeros((256, band_count), dtype=numpy.uint8)

	for k, v in src.colormap(1).items():
		if len(v) == 3:
			r, g, b = v
			a = 255
		else:
			r, g, b, a = v

		lut[k] = (r, g, b) if rgb else (r, g, b, a)

	if src.nodata is not None:
		ni = int(src.nodata)
		if 0 <= ni <= 255:
			if rgb:
				lut[ni] = (0, 0, 0)
			else:
				lut[ni] = (0, 0, 0, 0)

	block_h, block_w = src.block_shapes[0]

	with rasterio.open(dst_path, "w", **profile) as dst:
		if rgb:
			dst.colorinterp = (
				ColorInterp.red,
				ColorInterp.green,
				ColorInterp.blue,
			)
		else:
			dst.colorinterp = (
				ColorInterp.red,
				ColorInterp.green,
				ColorInterp.blue,
				ColorInterp.alpha,
			)

		for y in range(0, src.height, block_h):
			h = min(block_h, src.height - y)

			for x in range(0, src.width, block_w):
				window = Window(x, y, min(block_w, src.width - x), h)

				dst.write(lut[src.read(1, window=window)].transpose(2, 0, 1), window=window)


def is_paletted(src):
	return src.count == 1 and src.colorinterp[0] == ColorInterp.palette and src.colormap(1) is not None


def is_grayscale(src):
	return src.count == 1 and src.colorinterp[0] == ColorInterp.gray and src.colormap(1) is None


def is_gray_alpha(src):
  return src.count == 2 and src.colorinterp == (ColorInterp.gray, ColorInterp.alpha)


def is_rgb(src):
  return src.count == 3 and src.colorinterp == (ColorInterp.red, ColorInterp.green, ColorInterp.blue)


def is_rgba(src):
  return src.count == 4 and src.colorinterp == (ColorInterp.red, ColorInterp.green, ColorInterp.blue, ColorInterp.alpha)


def copy_data(src, dst_path, compression, output_driver="GTiff"):
	paletted = is_paletted(src)
	grayscale = is_grayscale(src)

	profile = src.profile.copy()
	profile.update(
		tiled=True,
		blockxsize=512,
		blockysize=512,
		bigtiff="YES",
	)

	if paletted:
		profile.update(photometric="PALETTE")
	elif grayscale:
		profile.update(photometric="MINISBLACK")
	elif src.count in (3, 4):
		profile.update(photometric="RGB")

	if output_driver:
		profile.update(
			driver=output_driver,
		)

	if compression:
		profile.update(
			compress="LZW",
			predictor=2,
		)

	with rasterio.open(dst_path, "w", **profile) as dst:
		for i in range(1, src.count + 1):
			dst.write(src.read(i), i)

		if paletted:
			dst.write_colormap(1, src.colormap(1))

			dst.colorinterp = (ColorInterp.palette,)
		elif grayscale:
			dst.colorinterp = (ColorInterp.gray,)
		elif src.count == 3:
			dst.colorinterp = (
				ColorInterp.red,
				ColorInterp.green,
				ColorInterp.blue,
			)
		elif src.count == 4:
			dst.colorinterp = (
				ColorInterp.red,
				ColorInterp.green,
				ColorInterp.blue,
				ColorInterp.alpha,
			)


def reproject_raster(src, dst_path, workers, compression, resampling, dst_crs, output_driver="GTiff"):
	transform, width, height = calculate_default_transform(
		src.crs, dst_crs, src.width, src.height, *src.bounds
	)

	paletted = is_paletted(src)
	grayscale = is_grayscale(src)

	profile = src.profile.copy()
	profile.update(
		crs=dst_crs,
		transform=transform,
		width=width,
		height=height,
		tiled=True,
		blockxsize=512,
		blockysize=512,
		bigtiff="YES",
	)

	if paletted:
		profile.update(photometric="PALETTE")
	elif grayscale:
		profile.update(photometric="MINISBLACK")

	if output_driver:
		profile.update(
			driver=output_driver,
		)

	if compression:
		profile.update(
			compress="LZW",
			predictor=2,
		)

	with rasterio.open(dst_path, "w", **profile) as dst:
		for b in range(1, src.count + 1):
			reproject(
				source=rasterio.band(src, b),
				destination=rasterio.band(dst, b),
				src_transform=src.transform,
				src_crs=src.crs,
				dst_transform=transform,
				dst_crs=dst_crs,
				resampling=resampling,
				num_threads=workers,
			)

		if paletted:
			dst.write_colormap(1, src.colormap(1))

			dst.colorinterp = (ColorInterp.palette,)
		elif grayscale:
			dst.colorinterp = (ColorInterp.gray,)
		elif src.count == 3:
			dst.colorinterp = (
				ColorInterp.red,
				ColorInterp.green,
				ColorInterp.blue,
			)
		elif src.count == 4:
			dst.colorinterp = (
				ColorInterp.red,
				ColorInterp.green,
				ColorInterp.blue,
				ColorInterp.alpha,
			)


# ========= MAIN =========
if __name__ == "__main__":
	if threading.current_thread() is threading.main_thread():
		setup_signals()

	parser = setup_command()

	args = parser.parse_args()

	input = args.input if args.input else args.output

	# Parse resampling
	resampling = Resampling.lanczos
	if resampling == "nearest":
		resampling = Resampling.nearest
	elif resampling == "bilinear":
		resampling = Resampling.bilinear
	elif resampling == "cubic":
		resampling = Resampling.cubic

	workers = max(1, args.workers)

	LOGGER.info(f"Reprojecting '{input}' -> '{args.output}'...")

	t0 = time.time()

	tmp_file_path = None

	with rasterio.open(input, "r") as src:
		if input == args.output:
			tmp_file_path = input.with_name(f"{input.stem}_{uuid.uuid4().hex}{input.suffix}")
		else:
			tmp_file_path = args.output

			tmp_file_path.unlink(missing_ok=True)

	if args.target:
			LOGGER.info(f"Creating VRT to {args.target}...")

			with WarpedVRT(src, crs=args.target, resampling=resampling) as vrt_src:
				if args.expand:
					LOGGER.info(f"Expanding {args.expand} '{input}' -> '{tmp_file_path}'...")

					expand_to_rgba(vrt_src, tmp_file_path, args.compression, args.expand == "rgb", args.output_driver)
				else:
					LOGGER.info(f"Copying '{input}' -> '{tmp_file_path}'...")

					copy_data(vrt_src, tmp_file_path, args.compression, args.output_driver)
	else:
			if args.expand:
				LOGGER.info(f"Expanding {args.expand} '{input}' -> '{tmp_file_path}'...")

				expand_to_rgba(src, tmp_file_path, args.compression, args.expand == "rgb", args.output_driver)
			else:
				LOGGER.info(f"Copying '{input}' -> '{tmp_file_path}'...")

				copy_data(src, tmp_file_path, args.compression, args.output_driver)

	if input == args.output:
		if tmp_file_path:
			tmp_file_path.replace(input)

	LOGGER.info(f"Reprojected '{input}' -> '{args.output}' in {time.time() - t0:.2f}s!")
