#!/usr/bin/env python3

from rasterio.windows import Window
from multiprocessing import Pool
from pathlib import Path
import threading
import argparse
import rasterio
import logging
import signal
import numpy
import time
import sys


# ========= LOGS =========
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)


# ========= DECODE =========
def rgb_to_data(args):
	rgb, base_val, interval = args

	rgb = rgb.astype(numpy.float64, copy=False)

	return base_val + (
		rgb[0] * 256 * 256 +
		rgb[1] * 256 +
		rgb[2]
	) * interval


if __name__ == "__main__":
	if threading.current_thread() is threading.main_thread():
		signal.signal(signal.SIGINT, lambda sig, frame: (
			LOGGER.info("Received 'SIGINT' signal. Exitting..."),

			sys.exit(0)
		))

		signal.signal(signal.SIGTERM, lambda sig, frame: (
			LOGGER.info("Received 'SIGTERM' signal. Exitting..."),

			sys.exit(0)
		))

	parser = argparse.ArgumentParser(description="Decode RGB (Terrain-RGB) GeoTIFF to DEM")
	parser.add_argument("-in", "--input", required=True, type=Path, help="Input RGB GeoTIFF")
	parser.add_argument("-out", "--output", required=True, type=Path, help="Output DEM GeoTIFF")
	parser.add_argument("-b", "--base-val", required=False, type=float, default=-10000, help="Base value")
	parser.add_argument("-i", "--interval", required=False, type=float, default=0.1, help="Interval")
	parser.add_argument("-w", "--workers", required=False, type=int, default=1, help="Number of worker processes")
	parser.add_argument("-c", "--compression", required=False, action="store_true", help="Enable compression for output GeoTIFF")

	args = parser.parse_args()

	LOGGER.info(f"Decode RGB (Terrain-RGB) GeoTIFF to DEM '{args.input}' -> '{args.output}'...")

	t0 = time.time()

	with rasterio.open(args.input) as src:
		profile = src.profile.copy()
		profile.update(
			dtype="float64",
			count=1,
			nodata=args.base_val,
			tiled=True,
			blockxsize=512,
			blockysize=512,
			bigtiff="YES",
		)

		if args.compression:
			profile.update(
				compress="LZW",
				predictor=3,
			)

		args.output.unlink(missing_ok=True)

		block_h, block_w = src.block_shapes[0]

		# ========= WINDOW GENERATOR =========
		def window_generator():
			for y in range(0, src.height, block_h):
				h = min(block_h, src.height - y)

				for x in range(0, src.width, block_w):
					yield Window(x, y, min(block_w, src.width - x), h)

		with rasterio.open(args.output, "w", **profile) as dst:
			workers = max(1, args.workers)

			# ========= SINGLE PROCESS =========
			if workers == 1:
				for w in window_generator():
					dst.write(rgb_to_data(src.read(window=w), args.base_val, args.interval), 1, window=w)
			# ========= MULTI PROCESS =========
			else:
				def task_gen():
					for w in window_generator():
						yield (
							src.read(window=w),
							args.base_val,
							args.interval,
						)

				with Pool(workers) as pool:
					for w, dem in zip(window_generator(), pool.imap(rgb_to_data, task_gen(), chunksize=1)):
						dst.write(dem, 1, window=w)

		LOGGER.info(f"Converted RGB (Terrain-RGB) GeoTIFF to DEM '{args.input}' -> '{args.output}' in {time.time() - t0:.2f}s!")
