#!/usr/bin/env python3

import os


# ========= ENV =========
os.environ["GDAL_NUM_THREADS"] = "ALL_CPUS"
os.environ["NUM_THREADS"] = "ALL_CPUS"


from rasterio.enums import ColorInterp
from rasterio.windows import Window
from multiprocessing import Pool
from pathlib import Path
import threading
import argparse
import rasterio
import logging
import signal
import numpy
import time
import sys


# ========= LOG =========
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)


# ========= SIGNALS =========
def setup_signals():
	signal.signal(signal.SIGINT, lambda sig, frame: (
		LOGGER.info("Received 'SIGINT' signal. Exitting..."),

		sys.exit(0)
	))

	signal.signal(signal.SIGTERM, lambda sig, frame: (
		LOGGER.info("Received 'SIGTERM' signal. Exitting..."),

		sys.exit(0)
	))


# ========= COMMAND =========
def setup_command():
	parser = argparse.ArgumentParser(description="Convert RGB raster (Terrain-RGB) to DEM raster")
	parser.add_argument("-in", "--input", required=True, type=Path, help="Input RGB raster file path")
	parser.add_argument("-out", "--output", required=True, type=Path, help="Output DEM raster file path")
	parser.add_argument("-b", "--base-val", required=False, type=float, default=-10000, help="Base value")
	parser.add_argument("-i", "--interval", required=False, type=float, default=0.1, help="Interval")
	parser.add_argument("-w", "--workers", required=False, type=int, default=1, help="Number of worker processes")
	parser.add_argument("-c", "--compression", required=False, action="store_true", help="Enable compression for output")
	parser.add_argument("-od", "--output-driver", required=False, type=str, default="GTiff", help="Output driver")

	return parser


# ========= DECODE =========
def rgb_to_data(args):
	rgb, window, convert_args = args

	rgb = rgb.astype(numpy.float64, copy=False)

	return convert_args["base_val"] + (
		rgb[0] * 256 * 256 +
		rgb[1] * 256 +
		rgb[2]
	) * convert_args["interval"], window


# ========= MAIN =========
if __name__ == "__main__":
	if threading.current_thread() is threading.main_thread():
		setup_signals()

	parser = setup_command()

	args = parser.parse_args()

	LOGGER.info(f"Converting RGB raster (Terrain-RGB) to DEM raster '{args.input}' -> '{args.output}'...")

	t0 = time.time()

	with rasterio.open(args.input, "r") as src:
		profile = src.profile.copy()
		profile.update(
			dtype="float64",
			count=1,
			photometric="MINISBLACK",
			nodata=args.base_val,
			tiled=True,
			blockxsize=512,
			blockysize=512,
			bigtiff="YES",
		)

		if args.output_driver:
			profile.update(
				driver=args.output_driver,
			)

		if args.compression:
			profile.update(
				compress="LZW",
				predictor=3,
			)

		args.output.unlink(missing_ok=True)

		with rasterio.open(args.output, "w", **profile) as dst:
			block_h, block_w = src.block_shapes[0]

			convert_args = {
				"base_val": args.base_val,
				"interval": args.interval,
			}

			def window_generator():
				for y in range(0, src.height, block_h):
					h = min(block_h, src.height - y)

					for x in range(0, src.width, block_w):
						window = Window(x, y, min(block_w, src.width - x), h)

						yield (src.read([1, 2, 3], window=window), window, convert_args)

			workers = max(1, args.workers)

			# Create workers
			if workers > 1:
				pool = Pool(workers)
			else:
				pool = None

			try:
				if pool:
					for data, window in pool.imap_unordered(rgb_to_data, window_generator()):
						dst.write(data, 1, window=window)
				else:
					for args in window_generator():
						data, window = rgb_to_data(args)

						dst.write(data, 1, window=window)
				
				dst.colorinterp = (ColorInterp.gray,)
			finally:
				if pool:
					pool.close()
					pool.join()

	LOGGER.info(f"Converted RGB raster (Terrain-RGB) to DEM raster '{args.input}' -> '{args.output}' in {time.time() - t0:.2f}s!")
